### ISSUE TITLE
Adding the specified count to the semaphore would cause it to exceed its maximum count

### ISSUE THREAD

**Issue by yAnn1ck-B** [mrchrisok/OandaV20#14]
First off, I have to say, this wrapper is great, I've been using it with great success.

However at some point I had the need to fire off these Rest20 commands as async Tasks and I occasionally received an error in StreamSession.cs mentioning:

> Adding the specified count to the semaphore would cause it to exceed its maximum count

I recognize these errors from when the database context of entity frame has not been properly disposed. However in this case there is no database context, so I am very curious as to what the reason could be and how I can fix it

**Comment by mrchrisok** [comment]
Hi yAnn1ck,

First:
The OandaV20 code and repo is no longer supported.
Please migrate to OandaV20.2.

Second:
The Semaphore class is Not used within OkonkwoOandaV20 library.
Any issue(s) you may be experiencing may be due to your code or environment.

That said, the Semaphore class is used in the sample app, OkonkwoOandaV20App.
It is also used in the test project, OkonkwoOandaV20Test.
In both cases, the semaphore usage was inelegant and not intended for production.

Please refer to Microsoft docs at the link below on the Semaphore class for detailed information on the proper use of the Semaphore.
If you need further assistance, please provide a code snippet.

Semaphore Link
https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphore.-ctor?view=netframework-4.8

Thanks,
Chris

**Comment by Jaco-JvZ** [comment]
Good day mrchrisok,

Can you possibly indicate where OandaV20.2 can be found, I would like to migrate but I don't know where to find this repo....

Regards,
JvZ

**Comment by mrchrisok** [comment]
OANDAV20.2 is available here: https://github.com/mrchrisok/OandaV20.2
