### ISSUE TITLE
Feature request: More info needed from Rest20.GetPendingOrderListAsync

### ISSUE THREAD

**Issue by mwok** [mrchrisok/OandaV20#3]
Hello Mrchrisok. I was testing 3 of the Get methods for Orders namely: Rest20.GetPendingOrderListAsync and Rest20.GetOrderListAsync and Rest20.GetOrderDetailsAsync . Currently Rest20.GetPendingOrderListAsync and Rest20.GetOrderListAsync using IOrder only exposes type, id, createTime, state and clientExtensions for use in my custom code.  However, when debugging I can see that there is more information being returned in each IOrder but is not exposed or accessible.  Would it be possible to include more information in IOrder such as at a minimum the following is also included: instrument/pair, units and price??  I note that it is possible to use Rest20.GetOrderListAsync to return a certain subset of Orders and then use  Rest20.GetOrderDetailsAsync to return the details for each orderID however, this is very slow especially with the time-delay speed bump and if there is a large number of orders that need to be reviewed over and over in real-time. Better is to expose more information one call from Rest20.GetPendingOrderListAsync .  Also I note that in previous versions in your code (mid-Jan 2018) sending the IOrder objects to strings individually from List of IOrder provided this missing information in IOrder which then could be parsed to extract instrument, units and price from IOrder.  But in the 02-Feb-2018 version of your code this capability was removed and sending to string just returns the current basic information. Another possible fix is to return IOrder object as string that can be used to extract other information needed without adding additional exposed methods in IOrder. Sorry for the long explanation of the problem.  I am new at C#.  I tried modifying your code to get more information out of  Rest20.GetPendingOrderListAsync but only ended up introducing errors.

**Comment by mrchrisok** [comment]
Mwok,

Based on the V20 api, the OandaV20 project contains the following order types:
- Order.cs 
  -  base/parent class for all order types
  - implements the IOrder interface

- EntryOrder.cs 
  -  subclass of Order.cs,
  -  parent of MarketOrder, MarketIfTouchedOrder, LimitOrder, StopOrder
- MarketOrder,cs
- MarketIfTouchedOrder.cs
- LimitOrder.cs
- StopOrder.cs

- ExitOrder.cs
  -  subclass of Order.cs,
  -  parent of TakeProfitOrder, StopLossOrder, TrailingStopLossOrder
- TakeProfitOrder,cs
- StopLossOrder.cs
- TrailingStopLossOrder.cs

The IOrder interface includes all of the properties common to all order types. The properties are: type, id, createTime, state, clientExtensions.

Adding instrument/pair, units and price to IOrder will be an incorrect change because it will force implementation of those properties on order types which do not have them.  For example: the Oanda definition of the TailingStopLossOrder type ([link](http://developer.oanda.com/rest-live-v20/order-df/)) does not have instrument, units or price.

GetPendingOrderListAsync, GetOrderListAsync, GetOrderDetailsAsync and a number of other operations  return a List<IOrder> if the Oanda response includes an order of a list of orders. The choice to use IOrder is because any of the Oanda order definitions may be returned from the Oanda endpoint. During deserialization, OrderFactor.cs is used to parse the response to ensure that each IOrder created contains the appropriate properties.

Regarding the speed bump, you are correct in identifying it as an issue to be addressed. The previous value (501 ms) is an over-looked hard configuration for the legacy Oanda REST api. I've reduced it to 11 ms per the Oanda V20 [best practices guidance](http://developer.oanda.com/rest-live-v20/best-practices/) for HTTP 1.1 persistent connections.

Let me know if you have any further questions/concerns,
Chris

**Comment by mwok** [comment]
Chris, 
Thanks for taking time to read my long rambling and for the thoughtful response to my question. I now understand why IOrder properties are what they are.  For my purposes when my code creates an order I just put instrument, price, units information into clientExtensions.comment.  This can be quickly checked with one call to either GetOrderListAsync or GetPendingOrderListAsync. Thanks for fixing the speed bump too.  The 501 ms was definitely too slow and now at 11 ms the code runs very well, fast and responsive!!
Regards,
Mike
